# =========================
#       BASICS
# =========================

source = colors.conf

# Монитор
monitor=HDMI-A-1,preferred,auto,1

# Wallpaper
exec-once = swww-daemon &
exec-once = waybar &
exec-once = mako &
exec-once = nm-applet &
exec-once = blueman-applet &
exec-once = kitty

# Input
input {
    kb_layout = us,ru
    kb_variant =
    kb_options = grp:alt_shift_toggle

    follow_mouse = 1
    sensitivity = 0.0
    touchpad {
        natural_scroll = yes
    }
}

# Windows
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    resize_on_border = true
    layout = dwindle
}

decoration {
    rounding = 8
}

animations {
    enabled = yes
}

# =========================
#      WINDOW RULES
# =========================

windowrulev2 = float, class:^thunar$
windowrulev2 = size 800 600, class:^thunar$
windowrulev2 = center, class:^thunar$

# =========================
#           END
# =========================

# =========================
#      KEYBINDS
# =========================

$mod = SUPER

bind = $mod, Backspace, exec, kitty
bind = $mod, Q, killactive,
bind = $mod, F, exec, rofi -show drun
bind = $mod, E, exec, thunar

bind = $mod SHIFT, F, togglefloating
bind = $mod, F11, fullscreen


# Lock Screen
bind = $mod, L, exec, ~/.config/hypr/scripts/screen-lock.sh

# Window Resize
bindm = SUPER, mouse:273, resizewindow

# Focus
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d

# Workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5

# Move windows
bindm = SUPER, mouse:272, movewindow
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

# Wallpaper change
bind = $mod CTRL, T, exec, ~/.local/bin/wallset
#bind = CTRL, 1, exec, swww img ~/Pictures/wall1.jpg --transition-type any
#bind = CTRL, 2, exec, swww img ~/Pictures/wall2.jpg --transition-type any
#bind = CTRL, 3, exec, swww img ~/Pictures/wall3.jpg --transition-type any

# Waybar reload
bind = $mod SHIFT, R, exec, ~/.config/waybar/scripts/launch.sh
