font_family      JetBrainsMono Nerd Font 15
symbol_map U+23FB-U+23FE,U+2B58 Symbols Nerd Font Mono
# Установить прозрачность фона
background_opacity 0.75 

# Если хочешь убрать аудиозвонок
enable_audio_bell no
